### ISSUE TITLE
Warn of dependency, build-dependency mismatch

### ISSUE THREAD

**Issue by mciantyre** [imxrt-rs/imxrt-rt#6]
This crate pairs a build script with a firmware library in order to create a target-specific runtime. To achieve this, users need to [keep their dependencies and build-dependencies in sync](https://docs.rs/imxrt-rt/0.1.0/imxrt_rt/#dependencies). For example, a package manifest that uses the 0.1 release should look like

```toml
[dependencies.imxrt-rt]
version = "0.1" # Firmware's dependency

[build-dependencies.imxrt-rt]
version = "0.1" # Build's dependency
```

Suppose a user changes the firmware's version to `"0.2"` but forgets to change the build's version. This could produce an incompatibility between the linker script and the firmware's runtime. In the best case, the build fails. But in the worst-case, the firmware acts wonky.

There's no need to handle this today. There's only one release of this crate, and this could only happen when there's a change that affects the linker script-runtime expectations. Nevertheless, we should consider ways to detect and warn of this mismatch. Helpful build failures are OK; wonky firmware, not so much.
